### ISSUE TITLE
Add Notification Manager

### ISSUE THREAD

**Issue by jsmith** [vusic/vusic#14]
We need to add a notification manager that will allow us to send information to the user.

We should basically duplicate the API Atom uses for their [NotficationManager](https://atom.io/docs/api/v1.9.4/NotificationManager#instance-addFatalError).

Additionally, this issue involves creating UI components. They should also be modeled off Atom's components and should behave in a similar manner (ie. most recent at the top, least recent on the bottom). When if dev mode, run something like `atom.notifications.addInfo('jacob', {dismissable: true})` to get a persistent notification so you extract the CSS.

# TODO
- [x] Add success, info, warning, error methods
- [ ] Add ability to add buttons
- [ ] Add clear all button if > 1 is displayed (like `Atom`)
- [x] Add ability to dismiss

**Comment by jsmith** [comment]
See https://github.com/euvl/vue-notification
