### ISSUE TITLE
Add Notification Manager

### ISSUE THREAD

**Issue by jsmith** [vusic/vusic#5]
<a href="https://github.com/jsmith"><img src="https://avatars3.githubusercontent.com/u/18077531?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsmith](https://github.com/jsmith)**
_Tuesday Oct 09, 2018 at 19:40 GMT_
_Originally opened as https://github.com/vuesic/vuesic/issues/14_

----

We need to add a notification manager that will allow us to send information to the user.

We should basically duplicate the API Atom uses for their [NotficationManager](https://atom.io/docs/api/v1.9.4/NotificationManager#instance-addFatalError).

Additionally, this issue involves creating UI components. They should also be modeled off Atom's components and should behave in a similar manner (ie. most recent at the top, least recent on the bottom). When if dev mode, run something like `atom.notifications.addInfo('jacob', {dismissable: true})` to get a persistent notification so you extract the CSS.

# TODO
- [ ] Add success, info, warning, error methods
- [ ] Add ability to add buttons
- [ ] Add clear all button if > 1 is displayed (like `Atom`)
- [ ] Add ability to dismiss

**Comment by jsmith** [comment]
<a href="https://github.com/jsmith"><img src="https://avatars3.githubusercontent.com/u/18077531?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jsmith](https://github.com/jsmith)**
_Thursday Oct 11, 2018 at 20:41 GMT_

----

See https://github.com/euvl/vue-notification
